# Generated by Django 3.0.8 on 2020-08-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detections',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Sensor'),
        ),
    ]
