# Generated by Django 3.0.8 on 2020-09-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200921_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Location'),
        ),
    ]
